const MOVING_TITLE = "MOVING_TITLE"; //电影名
const MOVING_LIST = "MOVING_LIST";  //上映电影列表
const MOVING_LOADING = "MOVING_LOADING";
const SEARCH_LOADING = "SEARCH_LOADING";
const PAGE_LOAD = "PAGE_LOAD";
const DETAIL_LOADING = "DETAIL_LOADING";
const UP_COMBODY = "UP_COMBODY";
const MOVIE_CITY = "MOVIE_CITY"; //上映的城市
const UP_COMING = "UP_COMING";
const LOAD_TOP250 = "LOAD_TOP250";
const MOVING_DETAIL = "MOVING_DETAIL";  //电影详情
const MOVING_ID = "MOVING_ID";  //电影id
const SEARCH_TEXT = "SEARCH_TEXT";
const SEARCH_LIST = "SEARCH_LIST";//搜索列表
const PAGE_START = "PAGE_START";//开始页
const MOVIE_COMMENT = "MOVIE_COMMENT";//影评
const MaxNum = "MaxNum"  //显示的最高条目
const TOP250_LOADING = 'TOP250_LOADING' //热门250loading

// export default {
//   MOVING_TITLE,
//   MOVING_LIST,
//   MOVING_LOADING,
//   SEARCH_LOADING,
//   PAGE_LOAD,
//   DETAIL_LOADING,
//   UP_COMBODY,
//   MOVIE_CITY,
//   UP_COMING,
//   LOAD_TOP250,
//   MOVING_DETAIL,
//   MOVING_ID,
//   SEARCH_TEXT,
//   SEARCH_LIST,
//   PAGE_START,
//   MOVIE_COMMENT

//   //  MOVING_TITLE : "MOVING_TITLE",//电影名
//   //  MOVING_LIST : "MOVING_LIST",
//   //  MOVING_LOADING : "MOVING_LOADING",
//   //  SEARCH_LOADING : "SEARCH_LOADING",
//   //  PAGE_LOAD : "PAGE_LOAD",
//   //  DETAIL_LOADING : "DETAIL_LOADING",
//   //  UP_COMBODY : "UP_COMBODY",
//   //  MOVIE_CITY : "MOVIE_CITY",//上映的城市
//   //  UP_COMING : "UP_COMING",
//   //  LOAD_TOP250 : "LOAD_TOP250",
//   //  MOVING_DETAIL : "MOVING_DETAIL",
//   //  MOVING_ID : "MOVING_ID",
//   //  SEARCH_TEXT : "SEARCH_TEXT",
//   //  SEARCH_LIST : "SEARCH_LIST",
//   //  PAGE_START : "PAGE_START",
//   //  MOVIE_COMMENT : "MOVIE_COMMENT"
// };
export {
  MOVING_TITLE,
  MOVING_LIST,
  MOVING_LOADING,
  SEARCH_LOADING,
  PAGE_LOAD,
  DETAIL_LOADING,
  UP_COMBODY,
  MOVIE_CITY,
  UP_COMING,
  LOAD_TOP250,
  MOVING_DETAIL,
  MOVING_ID,
  SEARCH_TEXT,
  SEARCH_LIST,
  PAGE_START,
  MOVIE_COMMENT,
  MaxNum,
  TOP250_LOADING
};
